version: '3'

services:
    portal-api:
        image: portal-api
        build:
            context: ./api/
        ports:
            - "5001:80"
        networks:
            - portal-network

    portal-frontend:
        image: portal-frontend
        build:
            context: ./frontend/
        ports:
            - "80:80"
        networks:
            - portal-network
        depends_on: 
            - portal-api

networks: 
    portal-network:
        driver: bridge